### ISSUE TITLE
"can't find '__main__' module"

### ISSUE THREAD

**Issue by jpinnix** [chrissimpkins/fontname.py#2]
Running this:
```
$ python /Users/[obfuscated]/Code/github/chrissimpkins/fontname.py "Hack DEV" Hack-Regular.ttf
```
produces this error:
```
/Users/[obfuscated]/.asdf/installs/python/3.6.2/bin/python3.6: 
can't find '__main__' module in 
'/Users/[obfuscated]/Code/github/chrissimpkins/fontname.py'
```
Any ideas?

**Comment by chrissimpkins** [comment]
Hmmm... Odd.  I can't reproduce this on macOS with Py3.7 or Py2.7 interpreters when executed with script in working directory or from a different working directory.  Is there any error message prior to that?  Does the script work if you execute it with the script in the working directory and the font file path outside of the working directory?

**Comment by chrissimpkins** [comment]
And have you modified the source file in any way?  I came up with this on SO:

https://stackoverflow.com/questions/42681801/python-cant-find-main-module/42681826 

but I can verify that the correct glyphs (U+0022) are displaying in the source in the master branch.

**Comment by jpinnix** [comment]
1. Placing the script and the font file in the same working directory works just fine. Thanks for making that suggestion. Apparently the caffeine hasn't kicked in yet. :-)
2. I'm trying 2 different versions of Hack from https://github.com/vikky49/patchedFonts-Ligatures

For the moment I'll just make sure to move the script into the appropriate working dir.

Thanks!!
Jeremy

**Comment by chrissimpkins** [comment]
No problem at all Jeremy.  Thanks for reporting it.  If you come across a solution that requires a modification in the source here, please reopen this thread and let me know (or submit a PR).  Happy to make a change if we can figure out what that change is.

**Comment by jpinnix** [comment]
And thank you so much for this helpful tool!

**Comment by chrissimpkins** [comment]
@jpinnix My pleasure!  Glad that it was of help.  I have been considering making a Python executable from this project.  This should take care of the problems that you are having here.  Keep an eye on the repo if you are interested in this tool.  I will let users know here when/if that is available.
