### ISSUE TITLE
Error: Unable to detect the font style 

### ISSUE THREAD

**Issue by blakeperdue** [chrissimpkins/fontname.py#5]
Running this on some TTF files gives the following error:

```
[fontname.py] Unable to detect the font style from the OpenType name table in '[FONT-NAME].ttf'. 
Unable to complete execution of the script. 
```

Does this mean my TTF files are corrupt or missing something or is this actually a bug? Wondering if I need to use TTX to do the recompile to get the name to change or if there's some changes I might be able to make to fontname.py to fix the issue. 

Thanks, and thanks for this cool repo!

**Comment by chrissimpkins** [comment]
The script pulls the OpenType name table ID 2 record from the font and uses that for the "style" definition.   "style" is formally known as "Font Subfamily name" in the OpenType specification and is commonly the weight-width definition ("Regular", "Bold", "Italic", "Bold Italic") for the font, though if you are dealing with an expanded family this can sometimes be handled a bit differently.  

https://github.com/chrissimpkins/fontname.py/blob/880152731626fe32f5d437617cd6a66c8f0ab213/fontname.py#L64-L68

 [Here is the spec on the name.ID2 field](https://docs.microsoft.com/en-us/typography/opentype/spec/name#name-ids).  The script searches across any name records that are defined in the font and pulls the subfamily name from the first one that it finds.  In your case, it seems that it can't find any nameID 2 record based on that error message. Without that it can't update the font family names properly.  

Are these fonts that you can share (even privately by email) with me?  If so, I'd be happy to have a look at how the name tables are structured so that we can troubleshoot this.

**Comment by blakeperdue** [comment]
Thank you, this is super helpful. I'm going to dig in and play with the script when I have time later tonight or tomorrow. The problem I'm running into is:

1) free fonts that were not created properly that I've collected over the years
2) fonts we licensed at my job that for some reason have different font names for each of the weights. For example, `VST Sans` is a our company font. Each weight, like `VST Sans Bold` shows up as a different font family because  the font name in the OTF file is `VST Sans Bold` instead of `VST Sans`. 

I could correct these manually, but am looking for an automated script I can run to do this quickly. I am writing a shell script that will go through all my font folders and just re-name all the font family names for each file it finds. I have organized my library into folders with proper names, so that part should work. I just need to figure out how to handle the fonts with missing table info.

I'll let you know what I turn up and also attach some example files that are open source licensed when I check back in. Thanks for your quick reply!

**Comment by chrissimpkins** [comment]
@blakeperdue This should get you started and can be batched on files with the same family name.  You can use this template to work with the subfamily name in the nameID2 record and other name table records (e.g. PostScript name etc).  Edit them before the `tt.save()` call.

**Note that it writes the files **in place** so execute on copies if you intend to keep the unmodified copies.**

`TTFont` comes from the fontTools Python package.  Requires Py3.6+ as of the v4.0.0+ releases of fontTools.

##### namer.py

```python
#!/usr/bin/env python3

import sys

from fontTools.ttLib import TTFont

# new family name for nameID 1
FAMILY_NAME = "[DEFINE FAMILY NAME HERE]"


def main(argv):
    for fontpath in argv:
        tt = TTFont(fontpath)
        
        for record in tt["name"].names:
            if record.nameID == 1:
            	record.string = FAMILY_NAME

        tt.save(fontpath)
        print(f"Updated '{fontpath}' family name to '{FAMILY_NAME}'")

if __name__ == "__main__":
    main(sys.argv[1:]
```


```
$ python3 namer.py [FONTPATH 1] [FONTPATH ...]
```

**Comment by blakeperdue** [comment]
Wow, this is great. Thank you so much. And a big thanks on the warning about backing up my files. Good call there and something I hadn't thought of, so thank you for preventing me from breaking my stuff 😅

**Comment by chrissimpkins** [comment]
Let me know if you run across any other issues.  Sometimes there are other problems that lead to issues with family grouping depending on your platform/application targets.

**Comment by blakeperdue** [comment]
So, the issue I had it turns out with many of my font files is:
* the family name has the style in it instead of just the family name
* the style string is empty (as that info was incorrectly added to the family name)

I modified your script for my purposes to collect the style string from the user and add it to the font file save. So, I can now run it to 1) name the font family in and 2) add the correct style to each file.

```
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
modified: fontname.py
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
@ fontname.py:70 @ def main(argv):
                style = str(record)
                break

        # if no style was provided, get it from the user
        if len(style) == 0:
            print(f"name = {namerecord_list[1]} / file = {font_path}")
            style = input("Enter style: ")
 
        # test that a style name was found in the OpenType tables of the font
        if len(style) == 0:
            sys.stderr.write(
@ fontname.py:99 @ def main(argv):
            for record in namerecord_list:
                if record.nameID == 1:
                    record.string = nameID1_string
                if record.nameID == 2:
                    record.string = style
                elif record.nameID == 4:
                    record.string = nameID4_string
                elif record.nameID == 6:
```

![image](https://user-images.githubusercontent.com/1642071/70883335-a6176180-1fa0-11ea-8a23-8bb34a603e9d.png)
