### ISSUE TITLE
FullName in CFF table is not changed

### ISSUE THREAD

**Issue by ddaanniiieeelll** [chrissimpkins/fontname.py#6]
I recently used your script and it works fatastic, however I realised, that the FullName in CFF table is not changed.
I had no problems whatsoever so far with renamed fonts, yet I’m still wondering what this entry in the CFF table does. 
So far all apps I tested the fonts with don't seem to care about this entry. Is it not important? Do I not need to change it?
For the sake of consistency I changed it manually with `ttx`, but I was wondering if there is a better way/it is necessary.

**Comment by chrissimpkins** [comment]
Good question.  I came across this in the [OpenType specification](https://docs.microsoft.com/en-us/typography/opentype/spec/name) for nameID 6:

> In a CFF OpenType font, there is no requirement that this name be the same as the font name in the CFF’s Name INDEX. Thus, the same CFF may be shared among multiple font components in a Font Collection. 

A good check might be to see what names show up in Adobe products when the names differ.  

Did the FullName value match the previous name table nameID 6 value of the font that you edited?

**Comment by ddaanniiieeelll** [comment]
> Did the FullName value match the previous name table nameID 6 value of the font that you edited?

Yes, that is how I noticed (I changed everything but the entry in the CFF table was still the previous name)

So far I had no problems using the fonts. Everything was displayed correctly on Mac and Win :)

**Comment by chrissimpkins** [comment]
93f719f42dc15a1e22c4190842668fb515465b02 should close this issue.  Mind having a look and let me know if this gets you to the CFF name updates that you needed to make manually?

**Comment by chrissimpkins** [comment]
I added support for FullName, FamilyName, and FontName fields in the CFF table.
